import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Usercard from '../userCard'

// MUI ui
import { styled } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';



const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className='header'>
                <Grid container spacing={8}> 
                    <Grid item xs={12} sx={{ display: 'inline-flex', justifyContent: 'flex-end' }}>
                        <Usercard
                            cardTitle={'Profile'}
                            cardSubTitle={['New', 'old', 'mamun']}
                        />
                        <Usercard
                            cardTitle={'Profile'}
                            cardSubTitle={['New', 'old', 'mamun']}
                        />
                    </Grid>
                </Grid>

            </header >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head> 

            <style style jsx > {` 
   
   .header {
          background: red;
          height:300px;
          background-image: url("paper.gif");
          background-image:url('https://images.unsplash.com/photo-1633075572879-143e7e39cee2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1993&q=80');
          background-size: cover;
          background-position: center;
        } 
    `}</style >

        </div >
    )
}

export default Home
