import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Usercard from '../components/userCard'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <header>
        <img className={styles.mainBanner} src="https://images.unsplash.com/photo-1569629743817-70d8db6c323b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2098&q=80" alt="" />
      </header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <Usercard
         cardTitle={'Become a partner'}
         cardSubTitle={'dddddddddddddd'}
         />
   
 
   
      </main>

   
    </div>
  )
}

export default Home
